(function(root){
const teams={CAR:'Carolina Panthers',SF:'San Francisco 49ers',KC:'Kansas City Chiefs',MIA:'Miami Dolphins',NO:'New Orleans Saints',ARI:'Arizona Cardinals',LAR:'Los Angeles Rams',PHI:'Philadelphia Eagles',JAX:'Jacksonville Jaguars',NYJ:'New York Jets',TB:'Tampa Bay Buccaneers',HOU:'Houston Texans',LV:'Las Vegas Raiders',DAL:'Dallas Cowboys',GB:'Green Bay Packers',DEN:'Denver Broncos',MIN:'Minnesota Vikings',CLE:'Cleveland Browns',CIN:'Cincinnati Bengals',NYG:'New York Giants',BUF:'Buffalo Bills',DET:'Detroit Lions',ATL:'Atlanta Falcons'};
// Original team key and Tim G. rows; 39-pool Week 2 corrected to #4 by Tim.
Object.assign(teams,{LAC:'Los Angeles Chargers',WAS:'Washington Commanders',PIT:'Pittsburgh Steelers',TEN:'Tennessee Titans',CHI:'Chicago Bears',NE:'New England Patriots',SEA:'Seattle Seahawks',BAL:'Baltimore Ravens',IND:'Indianapolis Colts'});
const teamKey={1:'CAR',2:'KC',3:'CIN',4:'DET',5:'MIA',6:'MIN',7:'BUF',8:'JAX',9:'LAC',10:'WAS',11:'HOU',12:'NO',13:'NYG',14:'SF',15:'PIT',16:'TEN',17:'CHI',18:'DEN',19:'PHI',20:'TB',21:'ATL',22:'CLE',23:'GB',24:'LAR',25:'NE',26:'SEA',27:'BAL',28:'IND',29:'LV',30:'NYJ',31:'ARI',32:'DAL'};
const assignmentNumbers={'39':[1,4,2,5,12,31,24,19,8,30,20,11,29,32,23,18,6,22],'50':[2,1,3,6,13,32,23,20,7,4,19,12,30,31,22,21,5,8]};
const assignments=Object.fromEntries(Object.entries(assignmentNumbers).map(([pool,numbers])=>[pool,numbers.map(number=>teamKey[number])]));
const normalize=s=>({WSH:'WAS',LA:'LAR',JAC:'JAX'}[s]||s);
function gameFor(data,code){for(const event of data?.events||[]){const c=event.competitions?.[0];const me=c?.competitors?.find(t=>normalize(t.team?.abbreviation)===code);if(!me)continue;const other=c.competitors.find(t=>t!==me);const status=c.status||event.status||{};return {me,other,status,date:c.date||event.date,score:me.score==null||me.score===''?null:Number(me.score),opponentScore:other?.score==null||other.score===''?null:Number(other.score),completed:status.type?.completed===true,state:status.type?.state||'pre'};}return null;}
function result(pool,g){if(!g)return {title:'Game not available',short:'Unconfirmed',detail:'The feed has no matching game yet. Schedule details or a bye may be pending.',hit:false};if(g.state==='pre')return {title:pool==='39'?'Chasing exactly 39.':'Chasing 50 or more.',short:'Upcoming',detail:pool==='39'?'Your team needs to finish with exactly 39 points.':'Your team needs to score at least 50 points.',hit:false};if(g.score===null||!Number.isFinite(g.score))return {title:'Score unavailable',short:'Unknown',detail:'Waiting for a valid score from the provider.',hit:false};const hit=pool==='39'?g.score===39:g.score>=50;if(g.completed)return {title:hit?'Pool win!':'No pool win',short:hit?'WIN':String(g.score)+' pts',detail:`Final score: ${g.score}–${g.opponentScore??'—'}. ${hit?'Your target was met.':'Your target was not met.'}`,hit};return {title:hit?(pool==='39'?'39 reached — hold it!':'50+ reached!'):pool==='39'&&g.score>39?'Past 39':`${Math.max(0,(pool==='39'?39:50)-g.score)} points to target`,short:hit?'TARGET':`${g.score} · Live`,detail:hit?'Target reached live. Final score confirms the pool result.':pool==='39'&&g.score>39?'Above the exact target. Awaiting the final score.':'Game in progress. Keep an eye on the score.',hit};}
const api={teams,teamKey,assignmentNumbers,assignments,normalize,gameFor,result};if(typeof module!=='undefined')module.exports=api;root.PoolCore=api;
})(typeof window==='undefined'?globalThis:window);
